### ISSUE TITLE
How to compute the accuracy?

### ISSUE THREAD

**Issue by TsuTikgiau** [jcoreyes/OP3#3]
Hello, thank you for your code! I'm wondering how to calculate the accuracy in Table 1 and 2 of the paper. In the code, I cannot find something similar to the accuracy. I also check the paper Reasoning About Physical Interactions with Object-Oriented Prediction and Planning but I cannot find the details of this metric like how to compute it, too. Does this repository contain the script to compute the accuracy? Thank you!

**Comment by Rishi-V** [comment]
The repo does contain the code to compute the accuracy for Table 1 and 2.
The code is in the block_stacking_env: https://github.com/jcoreyes/OP3/blob/ec3922ec3fbd2efd316eeda0877d99efab77524d/op3/envs/blocks/mujoco/block_stacking_env.py#L319
This is used in the mpc code when we compute our accuracy at the end of planning/execution: https://github.com/jcoreyes/OP3/blob/ec3922ec3fbd2efd316eeda0877d99efab77524d/exps/stack_exps/mpc_stack.py#L354
The goal data for each tower is provided in the repo as well in https://github.com/jcoreyes/OP3/tree/master/data/goals/stack_goals/manual_constructions.
