### ISSUE TITLE
Min and max number of objects in Single-Step Block Stacking training set.

### ISSUE THREAD

**Issue by ondrejbiza** [jcoreyes/OP3#4]
Hello,
I noticed that your downloadable training dataset seems to have between one and five objects.
But, the script `https://github.com/jcoreyes/OP3/blob/master/op3/envs/blocks/mujoco/stacking_generate_singlestep.py` has --min_objects and --max_objects set to four.
What is the range you used to train the models in your paper in Table 1?

Thank you!

**Comment by Rishi-V** [comment]
Really sorry for the late response, we used the downloadable training dataset for training our models for Table 1. The stacking_generate_singlestep.py script can be used to create a similar dataset or visualization purposes.
